name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:     # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ayush242808
          outputs: ./assets/snake.svg

      - name: Push to GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./assets/snake.svg
          git commit -m "Update snake animation"
          git push
